version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  splunk-1-var:
  splunk-1-etc:
  splunk-2-var:
  splunk-2-etc:

services:
  splunk-1:
    networks:
      splunknet:
        aliases:
          - splunk-1
    image: splunk/splunk:9.1.3
    container_name: splunk-1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=hello123
      - DEBUG=true
      - SPLUNK_UPGRADE=true
    ports:
      - 48000:8000
      - 49000:8089
    volumes:
      - splunk-1-var:/opt/splunk/var
      - splunk-1-etc:/opt/splunk/etc
    
  splunk-2:
    networks:
      splunknet:
        aliases:
          - splunk-2
    image: splunk/splunk:9.1.3
    container_name: splunk-2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=hello123
      - DEBUG=true
      - SPLUNK_UPGRADE=true
    ports:
      - 48001:8000
      - 49001:8089
    volumes:
      - splunk-2-var:/opt/splunk/var
      - splunk-2-etc:/opt/splunk/etc
