version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

volumes:
  splunk-1-var:
  splunk-1-etc:
  splunk-2-var:
  splunk-2-etc:

services:
  splunk-1:
    networks:
      splunknet:
        aliases:
          - splunk-1
    image: splunk/splunk:latest
    container_name: splunk-1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=hello123
      - DEBUG=true
      - SPLUNK_ROLE=splunk_search_head
    ports:
      - 48000:8000
      - 49000:8089
    volumes:
      - splunk-1-var:/opt/splunk/var
      - splunk-1-etc:/opt/splunk/etc
      - ./default.yml:/tmp/defaults/default.yml
    